# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false

r_packages:
    - covr
    - roxygen2
    - parallel
    - plyr
    - digest
    - foreach
    - knitr
before_script:
    - Rscript -e 'roxygen2::roxygenise(".")'

after_success:
    - Rscript -e 'library(covr); codecov()'
        

